// Code generated by protoc-gen-go. DO NOT EDIT.
// source: counter.proto

package grpc_file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CountReq struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountReq) Reset()         { *m = CountReq{} }
func (m *CountReq) String() string { return proto.CompactTextString(m) }
func (*CountReq) ProtoMessage()    {}
func (*CountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_counter_73509bd1fc449f91, []int{0}
}
func (m *CountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountReq.Unmarshal(m, b)
}
func (m *CountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountReq.Marshal(b, m, deterministic)
}
func (dst *CountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountReq.Merge(dst, src)
}
func (m *CountReq) XXX_Size() int {
	return xxx_messageInfo_CountReq.Size(m)
}
func (m *CountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CountReq.DiscardUnknown(m)
}

var xxx_messageInfo_CountReq proto.InternalMessageInfo

func (m *CountReq) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

type CountRes struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountRes) Reset()         { *m = CountRes{} }
func (m *CountRes) String() string { return proto.CompactTextString(m) }
func (*CountRes) ProtoMessage()    {}
func (*CountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_counter_73509bd1fc449f91, []int{1}
}
func (m *CountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRes.Unmarshal(m, b)
}
func (m *CountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRes.Marshal(b, m, deterministic)
}
func (dst *CountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRes.Merge(dst, src)
}
func (m *CountRes) XXX_Size() int {
	return xxx_messageInfo_CountRes.Size(m)
}
func (m *CountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRes.DiscardUnknown(m)
}

var xxx_messageInfo_CountRes proto.InternalMessageInfo

func (m *CountRes) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*CountReq)(nil), "grpc_file.CountReq")
	proto.RegisterType((*CountRes)(nil), "grpc_file.CountRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CounterClient is the client API for Counter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CounterClient interface {
	Count(ctx context.Context, in *CountReq, opts ...grpc.CallOption) (Counter_CountClient, error)
}

type counterClient struct {
	cc *grpc.ClientConn
}

func NewCounterClient(cc *grpc.ClientConn) CounterClient {
	return &counterClient{cc}
}

func (c *counterClient) Count(ctx context.Context, in *CountReq, opts ...grpc.CallOption) (Counter_CountClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Counter_serviceDesc.Streams[0], "/grpc_file.Counter/count", opts...)
	if err != nil {
		return nil, err
	}
	x := &counterCountClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Counter_CountClient interface {
	Recv() (*CountRes, error)
	grpc.ClientStream
}

type counterCountClient struct {
	grpc.ClientStream
}

func (x *counterCountClient) Recv() (*CountRes, error) {
	m := new(CountRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CounterServer is the server API for Counter service.
type CounterServer interface {
	Count(*CountReq, Counter_CountServer) error
}

func RegisterCounterServer(s *grpc.Server, srv CounterServer) {
	s.RegisterService(&_Counter_serviceDesc, srv)
}

func _Counter_Count_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CountReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CounterServer).Count(m, &counterCountServer{stream})
}

type Counter_CountServer interface {
	Send(*CountRes) error
	grpc.ServerStream
}

type counterCountServer struct {
	grpc.ServerStream
}

func (x *counterCountServer) Send(m *CountRes) error {
	return x.ServerStream.SendMsg(m)
}

var _Counter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_file.Counter",
	HandlerType: (*CounterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "count",
			Handler:       _Counter_Count_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "counter.proto",
}

func init() { proto.RegisterFile("counter.proto", fileDescriptor_counter_73509bd1fc449f91) }

var fileDescriptor_counter_73509bd1fc449f91 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x2f, 0xcd,
	0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x2f, 0x2a, 0x48, 0x8e,
	0x4f, 0xcb, 0xcc, 0x49, 0x55, 0x52, 0xe0, 0xe2, 0x70, 0x06, 0xc9, 0x05, 0xa5, 0x16, 0x0a, 0x89,
	0x70, 0xb1, 0x16, 0x97, 0x24, 0x16, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x38,
	0x4a, 0x32, 0x70, 0x15, 0xc5, 0x42, 0x02, 0x5c, 0xcc, 0x79, 0xa5, 0xb9, 0x50, 0x79, 0x10, 0xd3,
	0xc8, 0x8e, 0x8b, 0xdd, 0x19, 0x62, 0xb6, 0x90, 0x31, 0x17, 0x2b, 0xd8, 0x1a, 0x21, 0x61, 0x3d,
	0xb8, 0xf9, 0x7a, 0x30, 0xc3, 0xa5, 0xb0, 0x08, 0x16, 0x1b, 0x30, 0x26, 0xb1, 0x81, 0x5d, 0x64,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xcf, 0xe4, 0xc1, 0xa2, 0x00, 0x00, 0x00,
}
