// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package grpc_file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserReq) Reset()         { *m = ModifyUserReq{} }
func (m *ModifyUserReq) String() string { return proto.CompactTextString(m) }
func (*ModifyUserReq) ProtoMessage()    {}
func (*ModifyUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{1}
}
func (m *ModifyUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserReq.Unmarshal(m, b)
}
func (m *ModifyUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserReq.Marshal(b, m, deterministic)
}
func (dst *ModifyUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserReq.Merge(dst, src)
}
func (m *ModifyUserReq) XXX_Size() int {
	return xxx_messageInfo_ModifyUserReq.Size(m)
}
func (m *ModifyUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserReq proto.InternalMessageInfo

func (m *ModifyUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ModifyUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyUserRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserRep) Reset()         { *m = ModifyUserRep{} }
func (m *ModifyUserRep) String() string { return proto.CompactTextString(m) }
func (*ModifyUserRep) ProtoMessage()    {}
func (*ModifyUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{2}
}
func (m *ModifyUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserRep.Unmarshal(m, b)
}
func (m *ModifyUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserRep.Marshal(b, m, deterministic)
}
func (dst *ModifyUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserRep.Merge(dst, src)
}
func (m *ModifyUserRep) XXX_Size() int {
	return xxx_messageInfo_ModifyUserRep.Size(m)
}
func (m *ModifyUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserRep proto.InternalMessageInfo

type SelectUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserReq) Reset()         { *m = SelectUserReq{} }
func (m *SelectUserReq) String() string { return proto.CompactTextString(m) }
func (*SelectUserReq) ProtoMessage()    {}
func (*SelectUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{3}
}
func (m *SelectUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserReq.Unmarshal(m, b)
}
func (m *SelectUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserReq.Marshal(b, m, deterministic)
}
func (dst *SelectUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserReq.Merge(dst, src)
}
func (m *SelectUserReq) XXX_Size() int {
	return xxx_messageInfo_SelectUserReq.Size(m)
}
func (m *SelectUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserReq proto.InternalMessageInfo

func (m *SelectUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SelectUserRep struct {
	Users                *User    `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserRep) Reset()         { *m = SelectUserRep{} }
func (m *SelectUserRep) String() string { return proto.CompactTextString(m) }
func (*SelectUserRep) ProtoMessage()    {}
func (*SelectUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{4}
}
func (m *SelectUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserRep.Unmarshal(m, b)
}
func (m *SelectUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserRep.Marshal(b, m, deterministic)
}
func (dst *SelectUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserRep.Merge(dst, src)
}
func (m *SelectUserRep) XXX_Size() int {
	return xxx_messageInfo_SelectUserRep.Size(m)
}
func (m *SelectUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserRep proto.InternalMessageInfo

func (m *SelectUserRep) GetUsers() *User {
	if m != nil {
		return m.Users
	}
	return nil
}

type DeletetUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletetUserReq) Reset()         { *m = DeletetUserReq{} }
func (m *DeletetUserReq) String() string { return proto.CompactTextString(m) }
func (*DeletetUserReq) ProtoMessage()    {}
func (*DeletetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{5}
}
func (m *DeletetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletetUserReq.Unmarshal(m, b)
}
func (m *DeletetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletetUserReq.Marshal(b, m, deterministic)
}
func (dst *DeletetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletetUserReq.Merge(dst, src)
}
func (m *DeletetUserReq) XXX_Size() int {
	return xxx_messageInfo_DeletetUserReq.Size(m)
}
func (m *DeletetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletetUserReq proto.InternalMessageInfo

func (m *DeletetUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeletetUserRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletetUserRep) Reset()         { *m = DeletetUserRep{} }
func (m *DeletetUserRep) String() string { return proto.CompactTextString(m) }
func (*DeletetUserRep) ProtoMessage()    {}
func (*DeletetUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{6}
}
func (m *DeletetUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletetUserRep.Unmarshal(m, b)
}
func (m *DeletetUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletetUserRep.Marshal(b, m, deterministic)
}
func (dst *DeletetUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletetUserRep.Merge(dst, src)
}
func (m *DeletetUserRep) XXX_Size() int {
	return xxx_messageInfo_DeletetUserRep.Size(m)
}
func (m *DeletetUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletetUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_DeletetUserRep proto.InternalMessageInfo

type InsertUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserReq) Reset()         { *m = InsertUserReq{} }
func (m *InsertUserReq) String() string { return proto.CompactTextString(m) }
func (*InsertUserReq) ProtoMessage()    {}
func (*InsertUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{7}
}
func (m *InsertUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserReq.Unmarshal(m, b)
}
func (m *InsertUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserReq.Marshal(b, m, deterministic)
}
func (dst *InsertUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserReq.Merge(dst, src)
}
func (m *InsertUserReq) XXX_Size() int {
	return xxx_messageInfo_InsertUserReq.Size(m)
}
func (m *InsertUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserReq proto.InternalMessageInfo

func (m *InsertUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type InsertUserRep struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserRep) Reset()         { *m = InsertUserRep{} }
func (m *InsertUserRep) String() string { return proto.CompactTextString(m) }
func (*InsertUserRep) ProtoMessage()    {}
func (*InsertUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6875c316a38e96b0, []int{8}
}
func (m *InsertUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserRep.Unmarshal(m, b)
}
func (m *InsertUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserRep.Marshal(b, m, deterministic)
}
func (dst *InsertUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserRep.Merge(dst, src)
}
func (m *InsertUserRep) XXX_Size() int {
	return xxx_messageInfo_InsertUserRep.Size(m)
}
func (m *InsertUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserRep proto.InternalMessageInfo

func (m *InsertUserRep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserRep) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserRep) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserRep) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "grpc_file.User")
	proto.RegisterType((*ModifyUserReq)(nil), "grpc_file.ModifyUserReq")
	proto.RegisterType((*ModifyUserRep)(nil), "grpc_file.ModifyUserRep")
	proto.RegisterType((*SelectUserReq)(nil), "grpc_file.SelectUserReq")
	proto.RegisterType((*SelectUserRep)(nil), "grpc_file.SelectUserRep")
	proto.RegisterType((*DeletetUserReq)(nil), "grpc_file.DeletetUserReq")
	proto.RegisterType((*DeletetUserRep)(nil), "grpc_file.DeletetUserRep")
	proto.RegisterType((*InsertUserReq)(nil), "grpc_file.InsertUserReq")
	proto.RegisterType((*InsertUserRep)(nil), "grpc_file.InsertUserRep")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// 增
	InsertUser(ctx context.Context, in *InsertUserReq, opts ...grpc.CallOption) (*InsertUserRep, error)
	// 删
	DeletetUser(ctx context.Context, in *DeletetUserReq, opts ...grpc.CallOption) (*DeletetUserRep, error)
	// 查
	SelectUser(ctx context.Context, in *SelectUserReq, opts ...grpc.CallOption) (*SelectUserRep, error)
	// 改
	ModifyUser(ctx context.Context, in *ModifyUserReq, opts ...grpc.CallOption) (*ModifyUserRep, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) InsertUser(ctx context.Context, in *InsertUserReq, opts ...grpc.CallOption) (*InsertUserRep, error) {
	out := new(InsertUserRep)
	err := c.cc.Invoke(ctx, "/grpc_file.UserService/InsertUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeletetUser(ctx context.Context, in *DeletetUserReq, opts ...grpc.CallOption) (*DeletetUserRep, error) {
	out := new(DeletetUserRep)
	err := c.cc.Invoke(ctx, "/grpc_file.UserService/DeletetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SelectUser(ctx context.Context, in *SelectUserReq, opts ...grpc.CallOption) (*SelectUserRep, error) {
	out := new(SelectUserRep)
	err := c.cc.Invoke(ctx, "/grpc_file.UserService/SelectUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ModifyUser(ctx context.Context, in *ModifyUserReq, opts ...grpc.CallOption) (*ModifyUserRep, error) {
	out := new(ModifyUserRep)
	err := c.cc.Invoke(ctx, "/grpc_file.UserService/ModifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// 增
	InsertUser(context.Context, *InsertUserReq) (*InsertUserRep, error)
	// 删
	DeletetUser(context.Context, *DeletetUserReq) (*DeletetUserRep, error)
	// 查
	SelectUser(context.Context, *SelectUserReq) (*SelectUserRep, error)
	// 改
	ModifyUser(context.Context, *ModifyUserReq) (*ModifyUserRep, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_InsertUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).InsertUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_file.UserService/InsertUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).InsertUser(ctx, req.(*InsertUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeletetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeletetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_file.UserService/DeletetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeletetUser(ctx, req.(*DeletetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SelectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SelectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_file.UserService/SelectUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SelectUser(ctx, req.(*SelectUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ModifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ModifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_file.UserService/ModifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ModifyUser(ctx, req.(*ModifyUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_file.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertUser",
			Handler:    _UserService_InsertUser_Handler,
		},
		{
			MethodName: "DeletetUser",
			Handler:    _UserService_DeletetUser_Handler,
		},
		{
			MethodName: "SelectUser",
			Handler:    _UserService_SelectUser_Handler,
		},
		{
			MethodName: "ModifyUser",
			Handler:    _UserService_ModifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_6875c316a38e96b0) }

var fileDescriptor_user_6875c316a38e96b0 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x9b, 0x90, 0x80, 0x7a, 0x51, 0x5b, 0x74, 0x62, 0x30, 0x59, 0x88, 0x2c, 0x21, 0x75,
	0xca, 0x50, 0x24, 0x7e, 0x40, 0x05, 0x03, 0x03, 0x4b, 0x2a, 0x16, 0x16, 0x54, 0x92, 0x2b, 0x58,
	0x0a, 0x89, 0xb1, 0x03, 0x12, 0xff, 0x86, 0x9f, 0x8a, 0xec, 0x02, 0x89, 0x2b, 0x79, 0xcc, 0x16,
	0xdf, 0x7b, 0x7a, 0x2f, 0xf9, 0x72, 0x06, 0xf8, 0xd0, 0xa4, 0x72, 0xa9, 0xda, 0xae, 0xc5, 0xe9,
	0x8b, 0x92, 0xe5, 0xd3, 0x4e, 0xd4, 0xc4, 0x1f, 0x21, 0x7a, 0xd0, 0xa4, 0x70, 0x0e, 0xa1, 0xa8,
	0x58, 0x90, 0x05, 0xcb, 0xb8, 0x08, 0x45, 0x85, 0x08, 0x51, 0xb3, 0x7d, 0x23, 0x16, 0x66, 0xc1,
	0x72, 0x5a, 0xd8, 0x67, 0x64, 0x70, 0xb2, 0xad, 0x2a, 0x45, 0x5a, 0xb3, 0x23, 0x3b, 0xfe, 0x3b,
	0xe2, 0x19, 0xc4, 0xf2, 0xb5, 0x6d, 0x88, 0x45, 0x76, 0xbe, 0x3f, 0xf0, 0x12, 0x66, 0xf7, 0x6d,
	0x25, 0x76, 0x5f, 0xa6, 0xa1, 0xa0, 0xf7, 0x51, 0x4a, 0x16, 0x6e, 0x89, 0xe4, 0x17, 0x30, 0xdb,
	0x50, 0x4d, 0x65, 0xe7, 0x69, 0xe5, 0xd7, 0xae, 0x41, 0xe2, 0x25, 0xc4, 0x06, 0x8e, 0xb6, 0x9e,
	0x64, 0xb5, 0xc8, 0xff, 0xf1, 0xe4, 0xd6, 0xb2, 0x57, 0x79, 0x06, 0xf3, 0x1b, 0xaa, 0xa9, 0x23,
	0x6f, 0xf2, 0xe9, 0x81, 0x43, 0x1a, 0x04, 0x77, 0x8d, 0x26, 0xd5, 0x8d, 0x89, 0xe0, 0xa0, 0x44,
	0x8e, 0x51, 0xb2, 0xfa, 0x0e, 0x21, 0x31, 0xf9, 0x1b, 0x52, 0x9f, 0xa2, 0x24, 0x5c, 0x03, 0xf4,
	0xa5, 0xc8, 0x06, 0xcc, 0x9c, 0x0f, 0x4e, 0x7d, 0x8a, 0xe4, 0x13, 0xbc, 0x85, 0x64, 0xc0, 0x0b,
	0xcf, 0x07, 0x56, 0x97, 0x74, 0xea, 0x95, 0x4c, 0xcc, 0x1a, 0xa0, 0xff, 0xa1, 0xce, 0xab, 0x38,
	0x8b, 0x90, 0xfa, 0x94, 0xdf, 0x8c, 0x7e, 0x8d, 0x9c, 0x0c, 0x67, 0x85, 0x53, 0x9f, 0x22, 0xf9,
	0xe4, 0xf9, 0xd8, 0xde, 0xae, 0xab, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x13, 0x10, 0x3a,
	0x6b, 0x03, 0x00, 0x00,
}
